.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ARCHMAGE 1 "February 24, 2006"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
archmage \- CHM(Compiled HTML) Decompressor.
.SH SYNOPSIS
.B archmage
.I chmfile directory
.br
.SH DESCRIPTION
This manual page documents briefly the
.B archmage
command.  This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBarCHMage\fP is an extensible reader and decompiler for files in the
CHM format. This is the format used by Microsoft HTML Help, and is
also known as Compiled HTML. arCHMage is based on python-chm binding to 
chmlib from GnoCHM project.
.SH USAGE
.PP
Extract .chm to directory (directory will be created):

	archmage <chmfile> <directory>
.PP
.SH SEE ALSO
.PP
arCHMage Home Page: http://archmage.sf.net
.SH AUTHOR
.PP
arCHMage was written by Eugeny Korekin <az@ftc.ru>
.PP
This manual page was written by Basil Shubin <bashu@users.sourceforge.net>, 
for the Debian GNU/Linux system (but may be used by others).
