#!/usr/bin/env python
# -*- coding: utf-8 -*-

# arCHMage -- extensible reader and decompiler for files in the CHM format.
#
# Originally written by Eugeny Korekin <aaaz@users.sourceforge.net>
# Significantly modified by Basil Shubin <bashu@users.sourceforge.net>
#
# Copyright (c) 2003 Eugeny Korekin <aaaz@users.sourceforge.net>
# Copyright (c) 2005-2008 Basil Shubin <bashu@users.sourceforge.net>


"""arCHMage -- extensible reader and decompiler for files in the CHM format.

Usage: %(program)s [options] <chmfile> [destdir|destfile]
Where:

    -x / --extract
        Extracts CHM file into specified directory. If destination
        directory is ommited, than the new one will be created based
        on name of CHM file. This options is by defaut.
        
    -c format
    --convert format
        TODO: Put description here

    -p number
    --port=number
        Acts as HTTP server on specified port number, so you can read
        CHM file with your favourite browser. You can specify a directory
        with decompressed content.

    -d / --dump
        Dump HTML data as plain text into standard output.

    -V / --version
        Print version number and exit.

    -h / --help
        Print this text and exit.
"""

import os
import sys
import getopt

from archmod import __version__, message, error_msg

from archmod.CHM import *

program = sys.argv[0]

EXTRACT = 1		# Extract CHM content
HTTPSERVER = 2	# Act as standalone HTTP server
DUMPHTML = 3	# Dump CHM file as plain text
CHM2TXT = 4		# Convert CHM file into Single Text file
CHM2HTML = 5	# Convert CHM file into Single HTML file
CHM2PDF = 6		# Convert CHM file into PDF Document

COMMASPACE = ', '

def usage(code=0, msg=''):
	message(code, __doc__ % globals())
	message(code, msg)
	sys.exit(code)

def file2dir(filename):
	""" Convert filename.chm to filename_html """
	dirname = filename.rsplit('.', 1)[0] + '_' + 'html'
	return dirname
	
def output_file(filename, mode):
	""" Convert filename.chm to output filename """
	if mode == CHM2TXT:
		file_ext = 'txt'
	elif mode == CHM2HTML:
		file_ext = 'html'
	elif mode == CHM2PDF:
		file_ext = 'pdf'
	else:
		file_ext = 'output'
	output_filename = filename.rsplit('.', 1)[0] + '.' + file_ext
	return output_filename

def parseargs():
	try:
		opts, args = getopt.getopt(sys.argv[1:], 'xc:dp:Vh',
								   ['extract', 'convert', 'dump', 'port=', 'version', 'help'])
	except getopt.error, msg:
		usage(1, msg)

	class Options:
		mode = None        # EXTRACT or HTTPSERVER or other
		port = None        # HTTP port number
		chmfile = None     # CHM File to view/extract
		output = None      # Output file or directory

	options = Options()

	for opt, arg in opts:
		if opt in ('-h', '--help'):
			usage()
		elif opt in ('-V', '--version'):
			message(0, __version__)
			sys.exit(0)
		elif opt in ('-p', '--port'):
			if options.mode is not None:
				usage(1, '-x and -p are mutually exclusive')
			options.mode = HTTPSERVER
			try:
				options.port = int(arg)
			except ValueError, msg:
				usage(1, 'Invalid port number: %s' % msg)
		elif opt in ('-c', '--convert'):
			if options.mode is not None:
				usage(1, '-x, -p or -c are mutually exclusive')
			try:
				mode = str(arg)
				if mode == 'text':
					options.mode = CHM2TXT
				elif mode == 'html':
					options.mode = CHM2HTML
				elif mode == 'pdf':
					options.mode = CHM2PDF
				else:
					raise ValueError
			except ValueError, msg:
				usage(1, 'Invalid file format: %s' % mode)
		elif opt in ('-x', '--extract'):
			if options.mode is not None:
				usage(1, '-x and -p are mutually exclusive')
			options.mode = EXTRACT
		elif opt in ('-d', '--dump'):
			if options.mode is not None:
				usage(1, '-d should be used without any other options')
			options.mode = DUMPHTML
		else:
			assert False, (opt, arg)

    # Sanity checks
	if options.mode is None:
		options.mode = EXTRACT

	if not args:
		usage(1, 'No CHM file was specified!')
	else:
		options.chmfile = args.pop(0)

	# CHM content should be extracted
	if options.mode == EXTRACT:
		if not args:
			options.output = file2dir(options.chmfile)
		else:
			options.output = args.pop(0)
	elif options.mode in (CHM2TXT, CHM2HTML, CHM2PDF):
		if not args:
			options.output = output_file(options.chmfile, options.mode)
		else:
			options.output = args.pop(0)
			
	# Any other arguments are invalid
	if args:
		usage(1, 'Invalid arguments: ' + COMMASPACE.join(args))

	return options


def main():
	options = parseargs()
	if not os.path.exists(options.chmfile):
		error_msg('No such file: %s' % options.chmfile)
		sys.exit(1)

	# Check where is argument a CHM file or directory with decompressed
	# content. Depending on results make 'source' instance of CHMFile or
	# CHMDir class.
	source = os.path.isfile(options.chmfile) and \
			 CHMFile(options.chmfile) or CHMDir(options.chmfile)

	if options.mode == HTTPSERVER:
		CHMServer(source, port=options.port).run()
	elif options.mode == DUMPHTML:
		source.chm2text()
	elif options.mode == CHM2TXT:
		# TODO: add checking if file exists
		source.chm2text(open(options.output, 'w'))
	elif options.mode == CHM2HTML:
		source.chm2html(options.output)
	elif options.mode == EXTRACT:
		source.extract(options.output)

if __name__ == '__main__':
    main()
